services:
  db:
    image: postgres:12
    container_name: postgres
    environment:
      POSTGRES_USER: irusland
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
    - "5432:5432"
    volumes:
    - ./postgres-data:/var/lib/postgresql/data
